# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5fafaf240aa1cc72696ae00f2d3166d17a9aa3b3bb0cde6cbb06810729646c1283c6cf551972a3bf42986a2c35484c7abcb4427d473b8c8a616940918a3902

test:
  secret_key_base: 91ce1ab7911d38224171fdfaec51079629d6d6a6d102bcc38c70ff0e6a7941fd643f974445cb228eaef1ddabeab1f85fd2095359957b713a873377971c64f03c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
